import pymysql
db = pymysql.connect(host="localhost",user="root",passwd="12345678", db="sidekem")
cur = db.cursor()
cur.execute("SELECT id FROM `statistik_pekerjaan_kec` WHERE id LIKE '%3327%' ")
kecamatan=cur.fetchall()
for a in kecamatan:
    #Hitung Total Pekerjaan
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan IN ('Belum/Tidak Bekerja','Pelajar / Mahasiswa') ")
    pek1 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Mengurus Rumah Tangga' ")
    pek2 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Pelajar/Mahasiswa' ")
    pek3 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Pensiunan' ")
    pek4 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Pegawai Negeri Sipil' ")
    pek5 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Tentara Nasional Indonesia' ")
    pek6 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Kepolisian RI' ")
    pek7 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Perdagangan' ")
    pek8 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Petani/Pekebun' ")
    pek9 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Peternak' ")
    pek10 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan IN ('Nelayan/Perikanan','Nelayan / Perikanan') ")
    pek11 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Industri' ")
    pek12 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Konstruksi' ")
    pek13 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Transportasi' ")
    pek14 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Karyawan Swasta' ")
    pek15 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Karyawan BUMN' ")
    pek16 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Karyawan BUMD' ")
    pek17 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Karyawan Honorer' ")
    pek18 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Buruh Harian Lepas' ")
    pek19 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan IN ('Buruh Tani/Perkebunan','Buruh Tani / Perkebunan','Buruh Tani/Perkebunan Buruh Tani / Perkebunan','Petani / Pekebun') ")
    pek20 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan IN ('Buruh Nelayan/Perikanan','Buruh Nelayan / Perikanan') ")
    pek21 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Buruh Peternakan' ")
    pek22 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Pembantu Rumah Tangga' ")
    pek23 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Tukang Cukur' ")
    pek24 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Tukang Listrik' ")
    pek25 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Tukang Batu' ")
    pek26 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Tukang Kayu' ")
    pek27 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Tukang Sol Sepatu' ")
    pek28 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan IN ('Tukang Las/Pandai Besi','Tukang Las / Pandai Besi') ")
    pek29 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Tukang Jahit' ")
    pek30 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Penata Rambut' ")
    pek31 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Penata Rias' ")
    pek32 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Penata Busana' ")
    pek33 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Mekanik' ")
    pek34 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Tukang Gigi' ")
    pek35 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Seniman' ")
    pek36 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Tabib' ")
    pek37 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Paraji' ")
    pek38 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Perancang Busana' ")
    pek39 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Penterjemah' ")
    pek40 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Imam Masjid' ")
    pek41 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Pendeta' ")
    pek42 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Pastur' ")
    pek43 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Wartawan' ")
    pek44 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan IN ('Ustadz/Mubaligh','Ustadz / Mubaligh') ")
    pek45 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Juru Masak' ")
    pek46 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Promotor Acara' ")
    pek47 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Anggota DPR-RI' ")
    pek48 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Anggota DPD' ")
    pek49 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Anggota BPK' ")
    pek50 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Presiden' ")
    pek51 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Wakil Presiden' ")
    pek52 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Anggota Mahkamah Konstitusi' ")
    pek53 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Anggota Kabinet/Kementerian' ")
    pek54 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Duta Besar' ")
    pek55 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Gubernur' ")
    pek56 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Wakil Gubernur' ")
    pek57 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Bupati' ")
    pek58 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Wakil Bupati' ")
    pek59 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Walikota' ")
    pek60 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Wakil Walikota' ")
    pek61 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan IN ('Anggota DPRD Propinsi', 'ANGGOTA DPRD PROVINSI')")
    pek62 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan IN ('Anggota DPRD Kabupaten/Kota','Anggota DPRD Kabupaten / Kota', 'ANGGOTA DPRD KABUPATEN/KOTA') ")
    pek63 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Dosen' ")
    pek64 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Guru' ")
    pek65 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Pilot' ")
    pek66 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Pengacara' ")
    pek67 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Notaris' ")
    pek68 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Arsitek' ")
    pek69 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Akuntan' ")
    pek70 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Konsultan' ")
    pek71 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Dokter' ")
    pek72 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Bidan' ")
    pek73 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Perawat' ")
    pek74 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Apoteker' ")
    pek75 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan IN ('Psikiater/Psikolog','Psikiater / Psikolog') ")
    pek76 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Penyiar Televisi' ")
    pek77= str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Penyiar Radio' ")
    pek78 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Pelaut' ")
    pek79 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Peneliti' ")
    pek80 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Sopir' ")
    pek81 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Pialang' ")
    pek82 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Paranormal' ")
    pek83 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Pedagang' ")
    pek84 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Perangkat Desa' ")
    pek85 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Kepala Desa' ")
    pek86 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Biarawati' ")
    pek87 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan='Wiraswasta' ")
    pek88 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan LIKE '%Buruh Migr%' ")
    pek89 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND pekerjaan NOT IN ('Belum/Tidak Bekerja','Pelajar / Mahasiswa','Mengurus Rumah Tangga','Pelajar/Mahasiswa','Pensiunan','Pegawai Negeri Sipil','Tentara Nasional Indonesia','Kepolisian RI','Perdagangan','Petani/pekebun','Peternak','Nelayan/Perikanan','Nelayan / Perikanan','Industri','Konstruksi','Transportasi','Karyawan Swasta','Karyawan BUMN','Karyawan BUMD','Karyawan Honorer','Buruh Harian Lepas','Buruh Tani/Perkebunan','Buruh Tani / Perkebunan','Buruh Tani/Perkebunan Buruh Tani / Perkebunan','Petani / pekebun','Buruh Nelayan/Perikanan','Buruh Nelayan / Perikanan','Buruh Peternakan','Pembantu Rumah Tangga','Tukang Cukur','Tukang Listrik','Tukang Batu','Tukang Kayu','Tukang Sol Sepatu','Tukang Las/Pandai Besi','Tukang Las / Pandai Besi','Tukang Jahit','Penata Rambut','Penata Rias','Penata Busana','Mekanik','Tukang Gigi','Seniman','Tabib','Paraji','Perancang Busana','Penterjemah','Imam Masjid','Pendeta','Pastur','Wartawan','Ustadz/Mubaligh','Ustadz / Mubaligh','Juru Masak','Promotor Acara','Anggota DPR-RI','Anggota DPD','Anggota BPK','Presiden','Wakil Presiden','Anggota Mahkamah Konstitusi','Anggota Kabinet/Kementerian','Duta Besar','Gubernur','Wakil Gubernur','Bupati','Wakil Bupati','Walikota','Wakil Walikota','Anggota DPRD Propinsi', 'ANGGOTA DPRD PROVINSI','Anggota DPRD Kabupaten/Kota','Anggota DPRD Kabupaten / Kota', 'ANGGOTA DPRD KABUPATEN/KOTA','Dosen','Guru','Pilot','Pengacara','Notaris','Arsitek','Akuntan','Konsultan','Dokter','Bidan','Perawat','Apoteker','Psikiater/Psikolog','Psikiater / Psikolog','Penyiar Televisi','Penyiar Radio','Pelaut','Peneliti','Sopir','Pialang','Paranormal','Pedagang','Perangkat Desa','Kepala Desa','Biarawati','Wiraswasta','Buruh Migran') ")
    pek90 = str(cur.fetchone()[0])
    cur.execute("UPDATE `statistik_pekerjaan_kec` SET `belum/tidak_bekerja`='"+pek1+"', `mengurus_rumah_tangga`='"+pek2+"', `pelajar/mahasiswa`='"+pek3+"', `pensiunan`='"+pek4+"', `pegawai_negeri_sipil`='"+pek5+"', `tentara_nasional_indonesia`='"+pek6+"', `kepolisian_ri`='"+pek7+"', `perdagangan`='"+pek8+"', `petani/pekebun`='"+pek9+"', `peternak`='"+pek10+"', `nelayan/perikanan`='"+pek11+"', `industri`='"+pek12+"', `konstruksi`='"+pek13+"', `transportasi`='"+pek14+"', `karyawan_swasta`='"+pek15+"', `karyawan_bumn`='"+pek16+"', `karyawan_bumd`='"+pek17+"', `karyawan_honorer`='"+pek18+"', `buruh_harian_lepas`='"+pek19+"', `buruh_tani/perkebunan_buruh_tani_/_perkebunan`='"+pek20+"', `buruh_nelayan/perikanan`='"+pek21+"', `buruh_peternakan`='"+pek22+"', `pembantu_rumah_tangga`='"+pek23+"', `tukang_cukur`='"+pek24+"', `tukang_listrik`='"+pek25+"', `tukang_batu`='"+pek26+"', `tukang_kayu`='"+pek27+"', `tukang_sol_sepatu`='"+pek28+"', `tukang_las/pandai_besi`='"+pek29+"', `tukang_jahit`='"+pek30+"', `penata_rambut`='"+pek31+"', `penata_rias`='"+pek32+"', `penata_busana`='"+pek33+"', `mekanik`='"+pek34+"', `tukang_gigi`='"+pek35+"', `seniman`='"+pek36+"', `tabib`='"+pek37+"', `paraji`='"+pek38+"', `perancang_busana`='"+pek39+"', `penterjemah`='"+pek40+"', `imam_masjid`='"+pek41+"', `pendeta`='"+pek42+"', `pastur`='"+pek43+"', `wartawan`='"+pek44+"', `ustadz/mubaligh`='"+pek45+"', `juru_masak`='"+pek46+"', `promotor_acara`='"+pek47+"', `anggota_dpr-ri`='"+pek48+"', `anggota_dpd`='"+pek49+"', `anggota_bpk`='"+pek50+"', `presiden`='"+pek51+"', `wakil_presiden`='"+pek52+"', `anggota_mahkamah_konstitusi`='"+pek53+"', `anggota_kabinet/kementerian`='"+pek54+"', `duta_besar`='"+pek55+"', `gubernur`='"+pek56+"', `wakil_gubernur`='"+pek57+"', `bupati`='"+pek58+"', `wakil_bupati`='"+pek59+"', `walikota`='"+pek60+"', `wakil_walikota`='"+pek61+"', `anggota_dprd_propinsi`='"+pek62+"', `anggota_dprd_kabupaten/kota`='"+pek63+"', `dosen`='"+pek64+"', `guru`='"+pek65+"', `pilot`='"+pek66+"', `pengacara`='"+pek67+"', `notaris`='"+pek68+"', `arsitek`='"+pek69+"', `akuntan`='"+pek70+"', `konsultan`='"+pek71+"', `dokter`='"+pek72+"', `bidan`='"+pek73+"', `perawat`='"+pek74+"', `apoteker`='"+pek75+"', `psikiater/psikolog`='"+pek76+"', `penyiar_televisi`='"+pek77+"', `penyiar_radio`='"+pek78+"', `pelaut`='"+pek79+"', `peneliti`='"+pek80+"', `sopir`='"+pek81+"', `pialang`='"+pek82+"', `paranormal`='"+pek83+"', `pedagang`='"+pek84+"', `perangkat_desa`='"+pek85+"', `kepala_desa`='"+pek86+"', `biarawati`='"+pek87+"', `wiraswasta`='"+pek88+"', `buruh_migran`='"+pek89+"', `data_tdk_sesuai`='"+pek90+"' WHERE id='"+a[0]+"' ")
    db.commit()

    #Laki-laki
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan IN ('Belum/Tidak Bekerja','Pelajar / Mahasiswa') ")
    pek101 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Mengurus Rumah Tangga' ")
    pek102 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Pelajar/Mahasiswa' ")
    pek103 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Pensiunan' ")
    pek104 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Pegawai Negeri Sipil' ")
    pek105 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Tentara Nasional Indonesia' ")
    pek106 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Kepolisian RI' ")
    pek107 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Perdagangan' ")
    pek108 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Petani/pekebun' ")
    pek109 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Peternak' ")
    pek110 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan IN ('Nelayan/Perikanan','Nelayan / Perikanan') ")
    pek111 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Industri' ")
    pek112 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Konstruksi' ")
    pek113 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Transportasi' ")
    pek114 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Karyawan Swasta' ")
    pek115 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Karyawan BUMN' ")
    pek116 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Karyawan BUMD' ")
    pek117 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Karyawan Honorer' ")
    pek118 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Buruh Harian Lepas' ")
    pek119 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan IN ('Buruh Tani/Perkebunan','Buruh Tani / Perkebunan','Buruh Tani/Perkebunan Buruh Tani / Perkebunan','Petani / pekebun') ")
    pek120 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan IN ('Buruh Nelayan/Perikanan','Buruh Nelayan / Perikanan') ")
    pek121 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Buruh Peternakan' ")
    pek122 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Pembantu Rumah Tangga' ")
    pek123 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Tukang Cukur' ")
    pek124 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Tukang Listrik' ")
    pek125 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Tukang Batu' ")
    pek126 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Tukang Kayu' ")
    pek127 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Tukang Sol Sepatu' ")
    pek128 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan IN ('Tukang Las/Pandai Besi','Tukang Las / Pandai Besi') ")
    pek129 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Tukang Jahit' ")
    pek130 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Penata Rambut' ")
    pek131 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Penata Rias' ")
    pek132 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Penata Busana' ")
    pek133 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Mekanik' ")
    pek134 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Tukang Gigi' ")
    pek135 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Seniman' ")
    pek136 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Tabib' ")
    pek137 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Paraji' ")
    pek138 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Perancang Busana' ")
    pek139 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Penterjemah' ")
    pek140 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Imam Masjid' ")
    pek141 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Pendeta' ")
    pek142 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Pastur' ")
    pek143 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Wartawan' ")
    pek144 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan IN ('Ustadz/Mubaligh','Ustadz / Mubaligh') ")
    pek145 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Juru Masak' ")
    pek146 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Promotor Acara' ")
    pek147 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Anggota DPR-RI' ")
    pek148 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Anggota DPD' ")
    pek149 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Anggota BPK' ")
    pek150 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Presiden' ")
    pek151 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Wakil Presiden' ")
    pek152 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Anggota Mahkamah Konstitusi' ")
    pek153 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Anggota Kabinet/Kementerian' ")
    pek154 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Duta Besar' ")
    pek155 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Gubernur' ")
    pek156 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Wakil Gubernur' ")
    pek157 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Bupati' ")
    pek158 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Wakil Bupati' ")
    pek159 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Walikota' ")
    pek160 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Wakil Walikota' ")
    pek161 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan IN ('Anggota DPRD Propinsi', 'ANGGOTA DPRD PROVINSI') ")
    pek162 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan IN ('Anggota DPRD Kabupaten/Kota','Anggota DPRD Kabupaten / Kota', 'ANGGOTA DPRD KABUPATEN/KOTA') ")
    pek163 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Dosen' ")
    pek164 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Guru' ")
    pek165 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Pilot' ")
    pek166 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Pengacara' ")
    pek167 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Notaris' ")
    pek168 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Arsitek' ")
    pek169 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Akuntan' ")
    pek170 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Konsultan' ")
    pek171 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Dokter' ")
    pek172 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Bidan' ")
    pek173 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Perawat' ")
    pek174 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Apoteker' ")
    pek175 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan IN ('Psikiater/Psikolog','Psikiater / Psikolog') ")
    pek176 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Penyiar Televisi' ")
    pek177= str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Penyiar Radio' ")
    pek178 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Pelaut' ")
    pek179 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Peneliti' ")
    pek180 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Sopir' ")
    pek181 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Pialang' ")
    pek182 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Paranormal' ")
    pek183 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Pedagang' ")
    pek184 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Perangkat Desa' ")
    pek185 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Kepala Desa' ")
    pek186 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Biarawati' ")
    pek187 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan='Wiraswasta' ")
    pek188 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan LIKE '%Buruh Migr%' ")
    pek189 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'L%' AND pekerjaan NOT IN ('Belum/Tidak Bekerja','Pelajar / Mahasiswa','Mengurus Rumah Tangga','Pelajar/Mahasiswa','Pensiunan','Pegawai Negeri Sipil','Tentara Nasional Indonesia','Kepolisian RI','Perdagangan','Petani/pekebun','Peternak','Nelayan/Perikanan','Nelayan / Perikanan','Industri','Konstruksi','Transportasi','Karyawan Swasta','Karyawan BUMN','Karyawan BUMD','Karyawan Honorer','Buruh Harian Lepas','Buruh Tani/Perkebunan','Buruh Tani / Perkebunan','Buruh Tani/Perkebunan Buruh Tani / Perkebunan','Petani / pekebun','Buruh Nelayan/Perikanan','Buruh Nelayan / Perikanan','Buruh Peternakan','Pembantu Rumah Tangga','Tukang Cukur','Tukang Listrik','Tukang Batu','Tukang Kayu','Tukang Sol Sepatu','Tukang Las/Pandai Besi','Tukang Las / Pandai Besi','Tukang Jahit','Penata Rambut','Penata Rias','Penata Busana','Mekanik','Tukang Gigi','Seniman','Tabib','Paraji','Perancang Busana','Penterjemah','Imam Masjid','Pendeta','Pastur','Wartawan','Ustadz/Mubaligh','Ustadz / Mubaligh','Juru Masak','Promotor Acara','Anggota DPR-RI','Anggota DPD','Anggota BPK','Presiden','Wakil Presiden','Anggota Mahkamah Konstitusi','Anggota Kabinet/Kementerian','Duta Besar','Gubernur','Wakil Gubernur','Bupati','Wakil Bupati','Walikota','Wakil Walikota','Anggota DPRD Propinsi', 'ANGGOTA DPRD PROVINSI','Anggota DPRD Kabupaten/Kota','Anggota DPRD Kabupaten / Kota', 'ANGGOTA DPRD KABUPATEN/KOTA','Dosen','Guru','Pilot','Pengacara','Notaris','Arsitek','Akuntan','Konsultan','Dokter','Bidan','Perawat','Apoteker','Psikiater/Psikolog','Psikiater / Psikolog','Penyiar Televisi','Penyiar Radio','Pelaut','Peneliti','Sopir','Pialang','Paranormal','Pedagang','Perangkat Desa','Kepala Desa','Biarawati','Wiraswasta','Buruh Migran') ")
    pek190 = str(cur.fetchone()[0])
    cur.execute("UPDATE `statistik_pekerjaan_kec` SET `lk_belum/tidak_bekerja`='"+pek101+"', `lk_mengurus_rumah_tangga`='"+pek102+"', `lk_pelajar/mahasiswa`='"+pek103+"', `lk_pensiunan`='"+pek104+"', `lk_pegawai_negeri_sipil`='"+pek105+"', `lk_tentara_nasional_indonesia`='"+pek106+"', `lk_kepolisian_ri`='"+pek107+"', `lk_perdagangan`='"+pek108+"', `lk_petani/pekebun`='"+pek109+"', `lk_peternak`='"+pek110+"', `lk_nelayan/perikanan`='"+pek111+"', `lk_industri`='"+pek112+"', `lk_konstruksi`='"+pek113+"', `lk_transportasi`='"+pek114+"', `lk_karyawan_swasta`='"+pek115+"', `lk_karyawan_bumn`='"+pek116+"', `lk_karyawan_bumd`='"+pek117+"', `lk_karyawan_honorer`='"+pek118+"', `lk_buruh_harian_lepas`='"+pek119+"', `lk_buruh_tani/perkebunan_buruh_tani_/_perkebunan`='"+pek120+"', `lk_buruh_nelayan/perikanan`='"+pek121+"', `lk_buruh_peternakan`='"+pek122+"', `lk_pembantu_rumah_tangga`='"+pek123+"', `lk_tukang_cukur`='"+pek124+"', `lk_tukang_listrik`='"+pek125+"', `lk_tukang_batu`='"+pek126+"', `lk_tukang_kayu`='"+pek127+"', `lk_tukang_sol_sepatu`='"+pek128+"', `lk_tukang_las/pandai_besi`='"+pek129+"', `lk_tukang_jahit`='"+pek130+"', `lk_penata_rambut`='"+pek131+"', `lk_penata_rias`='"+pek132+"', `lk_penata_busana`='"+pek133+"', `lk_mekanik`='"+pek134+"', `lk_tukang_gigi`='"+pek135+"', `lk_seniman`='"+pek136+"', `lk_tabib`='"+pek137+"', `lk_paraji`='"+pek138+"', `lk_perancang_busana`='"+pek139+"', `lk_penterjemah`='"+pek140+"', `lk_imam_masjid`='"+pek141+"', `lk_pendeta`='"+pek142+"', `lk_pastur`='"+pek143+"', `lk_wartawan`='"+pek144+"', `lk_ustadz/mubaligh`='"+pek145+"', `lk_juru_masak`='"+pek146+"', `lk_promotor_acara`='"+pek147+"', `lk_anggota_dpr-ri`='"+pek148+"', `lk_anggota_dpd`='"+pek149+"', `lk_anggota_bpk`='"+pek150+"', `lk_presiden`='"+pek151+"', `lk_wakil_presiden`='"+pek152+"', `lk_anggota_mahkamah_konstitusi`='"+pek153+"', `lk_anggota_kabinet/kementerian`='"+pek154+"', `lk_duta_besar`='"+pek155+"', `lk_gubernur`='"+pek156+"', `lk_wakil_gubernur`='"+pek157+"', `lk_bupati`='"+pek158+"', `lk_wakil_bupati`='"+pek159+"', `lk_walikota`='"+pek160+"', `lk_wakil_walikota`='"+pek161+"', `lk_anggota_dprd_propinsi`='"+pek162+"', `lk_anggota_dprd_kabupaten/kota`='"+pek163+"', `lk_dosen`='"+pek164+"', `lk_guru`='"+pek165+"', `lk_pilot`='"+pek166+"', `lk_pengacara`='"+pek167+"', `lk_notaris`='"+pek168+"', `lk_arsitek`='"+pek169+"', `lk_akuntan`='"+pek170+"', `lk_konsultan`='"+pek171+"', `lk_dokter`='"+pek172+"', `lk_bidan`='"+pek173+"', `lk_perawat`='"+pek174+"', `lk_apoteker`='"+pek175+"', `lk_psikiater/psikolog`='"+pek176+"', `lk_penyiar_televisi`='"+pek177+"', `lk_penyiar_radio`='"+pek178+"', `lk_pelaut`='"+pek179+"', `lk_peneliti`='"+pek180+"', `lk_sopir`='"+pek181+"', `lk_pialang`='"+pek182+"', `lk_paranormal`='"+pek183+"', `lk_pedagang`='"+pek184+"', `lk_perangkat_desa`='"+pek185+"', `lk_kepala_desa`='"+pek186+"', `lk_biarawati`='"+pek187+"', `lk_wiraswasta`='"+pek188+"', `lk_buruh_migran`='"+pek189+"', `lk_data_tdk_sesuai`='"+pek190+"' WHERE id='"+a[0]+"' ")
    db.commit()

    #Perempuan
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan IN ('Belum/Tidak Bekerja','Pelajar / Mahasiswa') ")
    pek201 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Mengurus Rumah Tangga' ")
    pek202 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Pelajar/Mahasiswa' ")
    pek203 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Pensiunan' ")
    pek204 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Pegawai Negeri Sipil' ")
    pek205 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Tentara Nasional Indonesia' ")
    pek206 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Kepolisian RI' ")
    pek207 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Perdagangan' ")
    pek208 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Petani/pekebun' ")
    pek209 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Peternak' ")
    pek210 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan IN ('Nelayan/Perikanan','Nelayan / Perikanan') ")
    pek211 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Industri' ")
    pek212 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Konstruksi' ")
    pek213 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Transportasi' ")
    pek214 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Karyawan Swasta' ")
    pek215 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Karyawan BUMN' ")
    pek216 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Karyawan BUMD' ")
    pek217 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Karyawan Honorer' ")
    pek218 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Buruh Harian Lepas' ")
    pek219 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan IN ('Buruh Tani/Perkebunan','Buruh Tani / Perkebunan','Buruh Tani/Perkebunan Buruh Tani / Perkebunan','Petani / pekebun') ")
    pek220 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan IN ('Buruh Nelayan/Perikanan','Buruh Nelayan / Perikanan') ")
    pek221 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Buruh Peternakan' ")
    pek222 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Pembantu Rumah Tangga' ")
    pek223 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Tukang Cukur' ")
    pek224 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Tukang Listrik' ")
    pek225 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Tukang Batu' ")
    pek226 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Tukang Kayu' ")
    pek227 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Tukang Sol Sepatu' ")
    pek228 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan IN ('Tukang Las/Pandai Besi','Tukang Las / Pandai Besi') ")
    pek229 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Tukang Jahit' ")
    pek230 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Penata Rambut' ")
    pek231 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Penata Rias' ")
    pek232 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Penata Busana' ")
    pek233 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Mekanik' ")
    pek234 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Tukang Gigi' ")
    pek235 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Seniman' ")
    pek236 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Tabib' ")
    pek237 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Paraji' ")
    pek238 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Perancang Busana' ")
    pek239 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Penterjemah' ")
    pek240 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Imam Masjid' ")
    pek241 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Pendeta' ")
    pek242 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Pastur' ")
    pek243 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Wartawan' ")
    pek244 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan IN ('Ustadz/Mubaligh','Ustadz / Mubaligh') ")
    pek245 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Juru Masak' ")
    pek246 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Promotor Acara' ")
    pek247 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Anggota DPR-RI' ")
    pek248 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Anggota DPD' ")
    pek249 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Anggota BPK' ")
    pek250 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Presiden' ")
    pek251 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Wakil Presiden' ")
    pek252 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Anggota Mahkamah Konstitusi' ")
    pek253 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Anggota Kabinet/Kementerian' ")
    pek254 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Duta Besar' ")
    pek255 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Gubernur' ")
    pek256 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Wakil Gubernur' ")
    pek257 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Bupati' ")
    pek258 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Wakil Bupati' ")
    pek259 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Walikota' ")
    pek260 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Wakil Walikota' ")
    pek261 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan IN ('Anggota DPRD Propinsi', 'ANGGOTA DPRD PROVINSI') ")
    pek262 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan IN ('Anggota DPRD Kabupaten/Kota','Anggota DPRD Kabupaten / Kota', 'ANGGOTA DPRD KABUPATEN/KOTA') ")
    pek263 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Dosen' ")
    pek264 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Guru' ")
    pek265 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Pilot' ")
    pek266 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Pengacara' ")
    pek267 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Notaris' ")
    pek268 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Arsitek' ")
    pek269 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Akuntan' ")
    pek270 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Konsultan' ")
    pek271 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Dokter' ")
    pek272 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Bidan' ")
    pek273 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Perawat' ")
    pek274 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Apoteker' ")
    pek275 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan IN ('Psikiater/Psikolog','Psikiater / Psikolog') ")
    pek276 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Penyiar Televisi' ")
    pek277= str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Penyiar Radio' ")
    pek278 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Pelaut' ")
    pek279 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Peneliti' ")
    pek280 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Sopir' ")
    pek281 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Pialang' ")
    pek282 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Paranormal' ")
    pek283 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Pedagang' ")
    pek284 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Perangkat Desa' ")
    pek285 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Kepala Desa' ")
    pek286 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Biarawati' ")
    pek287 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan='Wiraswasta' ")
    pek288 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan LIKE '%Buruh Migr%' ")
    pek289 = str(cur.fetchone()[0])
    cur.execute("SELECT COUNT(no) FROM `datapenduduk-33` WHERE kec_id='"+a[0]+"' AND jk LIKE 'P%' AND pekerjaan NOT IN ('Belum/Tidak Bekerja','Pelajar / Mahasiswa','Mengurus Rumah Tangga','Pelajar/Mahasiswa','Pensiunan','Pegawai Negeri Sipil','Tentara Nasional Indonesia','Kepolisian RI','Perdagangan','Petani/pekebun','Peternak','Nelayan/Perikanan','Nelayan / Perikanan','Industri','Konstruksi','Transportasi','Karyawan Swasta','Karyawan BUMN','Karyawan BUMD','Karyawan Honorer','Buruh Harian Lepas','Buruh Tani/Perkebunan','Buruh Tani / Perkebunan','Buruh Tani/Perkebunan Buruh Tani / Perkebunan','Petani / pekebun','Buruh Nelayan/Perikanan','Buruh Nelayan / Perikanan','Buruh Peternakan','Pembantu Rumah Tangga','Tukang Cukur','Tukang Listrik','Tukang Batu','Tukang Kayu','Tukang Sol Sepatu','Tukang Las/Pandai Besi','Tukang Las / Pandai Besi','Tukang Jahit','Penata Rambut','Penata Rias','Penata Busana','Mekanik','Tukang Gigi','Seniman','Tabib','Paraji','Perancang Busana','Penterjemah','Imam Masjid','Pendeta','Pastur','Wartawan','Ustadz/Mubaligh','Ustadz / Mubaligh','Juru Masak','Promotor Acara','Anggota DPR-RI','Anggota DPD','Anggota BPK','Presiden','Wakil Presiden','Anggota Mahkamah Konstitusi','Anggota Kabinet/Kementerian','Duta Besar','Gubernur','Wakil Gubernur','Bupati','Wakil Bupati','Walikota','Wakil Walikota','Anggota DPRD Propinsi', 'ANGGOTA DPRD PROVINSI','Anggota DPRD Kabupaten/Kota','Anggota DPRD Kabupaten / Kota', 'ANGGOTA DPRD KABUPATEN/KOTA','Dosen','Guru','Pilot','Pengacara','Notaris','Arsitek','Akuntan','Konsultan','Dokter','Bidan','Perawat','Apoteker','Psikiater/Psikolog','Psikiater / Psikolog','Penyiar Televisi','Penyiar Radio','Pelaut','Peneliti','Sopir','Pialang','Paranormal','Pedagang','Perangkat Desa','Kepala Desa','Biarawati','Wiraswasta','Buruh Migran') ")
    pek290 = str(cur.fetchone()[0])
    cur.execute("UPDATE `statistik_pekerjaan_kec` SET `pr_belum/tidak_bekerja`='"+pek201+"', `pr_mengurus_rumah_tangga`='"+pek202+"', `pr_pelajar/mahasiswa`='"+pek203+"', `pr_pensiunan`='"+pek204+"', `pr_pegawai_negeri_sipil`='"+pek205+"', `pr_tentara_nasional_indonesia`='"+pek206+"', `pr_kepolisian_ri`='"+pek207+"', `pr_perdagangan`='"+pek208+"', `pr_petani/pekebun`='"+pek209+"', `pr_peternak`='"+pek210+"', `pr_nelayan/perikanan`='"+pek211+"', `pr_industri`='"+pek212+"', `pr_konstruksi`='"+pek213+"', `pr_transportasi`='"+pek214+"', `pr_karyawan_swasta`='"+pek215+"', `pr_karyawan_bumn`='"+pek216+"', `pr_karyawan_bumd`='"+pek217+"', `pr_karyawan_honorer`='"+pek218+"', `pr_buruh_harian_lepas`='"+pek219+"', `pr_buruh_tani/perkebunan_buruh_tani_/_perkebunan`='"+pek220+"', `pr_buruh_nelayan/perikanan`='"+pek221+"', `pr_buruh_peternakan`='"+pek222+"', `pr_pembantu_rumah_tangga`='"+pek223+"', `pr_tukang_cukur`='"+pek224+"', `pr_tukang_listrik`='"+pek225+"', `pr_tukang_batu`='"+pek226+"', `pr_tukang_kayu`='"+pek227+"', `pr_tukang_sol_sepatu`='"+pek228+"', `pr_tukang_las/pandai_besi`='"+pek229+"', `pr_tukang_jahit`='"+pek230+"', `pr_penata_rambut`='"+pek231+"', `pr_penata_rias`='"+pek232+"', `pr_penata_busana`='"+pek233+"', `pr_mekanik`='"+pek234+"', `pr_tukang_gigi`='"+pek235+"', `pr_seniman`='"+pek236+"', `pr_tabib`='"+pek237+"', `pr_paraji`='"+pek238+"', `pr_perancang_busana`='"+pek239+"', `pr_penterjemah`='"+pek240+"', `pr_imam_masjid`='"+pek241+"', `pr_pendeta`='"+pek242+"', `pr_pastur`='"+pek243+"', `pr_wartawan`='"+pek244+"', `pr_ustadz/mubaligh`='"+pek245+"', `pr_juru_masak`='"+pek246+"', `pr_promotor_acara`='"+pek247+"', `pr_anggota_dpr-ri`='"+pek248+"', `pr_anggota_dpd`='"+pek249+"', `pr_anggota_bpk`='"+pek250+"', `pr_presiden`='"+pek251+"', `pr_wakil_presiden`='"+pek252+"', `pr_anggota_mahkamah_konstitusi`='"+pek253+"', `pr_anggota_kabinet/kementerian`='"+pek254+"', `pr_duta_besar`='"+pek255+"', `pr_gubernur`='"+pek256+"', `pr_wakil_gubernur`='"+pek257+"', `pr_bupati`='"+pek258+"', `pr_wakil_bupati`='"+pek259+"', `pr_walikota`='"+pek260+"', `pr_wakil_walikota`='"+pek261+"', `pr_anggota_dprd_propinsi`='"+pek262+"', `pr_anggota_dprd_kabupaten/kota`='"+pek263+"', `pr_dosen`='"+pek264+"', `pr_guru`='"+pek265+"', `pr_pilot`='"+pek266+"', `pr_pengacara`='"+pek267+"', `pr_notaris`='"+pek268+"', `pr_arsitek`='"+pek269+"', `pr_akuntan`='"+pek270+"', `pr_konsultan`='"+pek271+"', `pr_dokter`='"+pek272+"', `pr_bidan`='"+pek273+"', `pr_perawat`='"+pek274+"', `pr_apoteker`='"+pek275+"', `pr_psikiater/psikolog`='"+pek276+"', `pr_penyiar_televisi`='"+pek277+"', `pr_penyiar_radio`='"+pek278+"', `pr_pelaut`='"+pek279+"', `pr_peneliti`='"+pek280+"', `pr_sopir`='"+pek281+"', `pr_pialang`='"+pek282+"', `pr_paranormal`='"+pek283+"', `pr_pedagang`='"+pek284+"', `pr_perangkat_desa`='"+pek285+"', `pr_kepala_desa`='"+pek286+"', `pr_biarawati`='"+pek287+"', `pr_wiraswasta`='"+pek288+"', `pr_buruh_migran`='"+pek289+"', `pr_data_tdk_sesuai`='"+pek290+"' WHERE id='"+a[0]+"' ")
    db.commit()