

#DATAKEMISKINAN



#STATISTIK KEMISKINAN
@appdesa.route('/statistikperumahan')
def statistikperumahan():
	if 'pengguna' in session:
		if session['pemerintah']=='desa':
			#HITUNG STATUS BANGUNAN
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND status_bangunan LIKE '1' ")
			hasilbangunanmiliksendiri=cur.fetchone()
			session['bangunanmiliksendiri']=str(hasilbangunanmiliksendiri[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND status_bangunan LIKE '2' ")
			hasilbangunansewakontrak=cur.fetchone()
			session['bangunansewakontrak']=str(hasilbangunansewakontrak[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND status_bangunan LIKE '3' ")
			hasilbangunanbebassewa=cur.fetchone()
			session['bangunanbebassewa']=str(hasilbangunanbebassewa[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND status_bangunan LIKE '4' ")
			hasilbangunandinas=cur.fetchone()
			session['bangunandinas']=str(hasilbangunandinas[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND status_bangunan LIKE '5' ")
			hasilbangunanlainnya=cur.fetchone()
			session['bangunanlainnya']=str(hasilbangunanlainnya[0])

			#HITUNG STATUS LAHAN
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND status_lahan LIKE '1' ")
			hasillahanmiliksendiri=cur.fetchone()
			session['lahanmiliksendiri']=str(hasillahanmiliksendiri[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND status_lahan LIKE '2' ")
			hasillahanmilikoranglain=cur.fetchone()
			session['lahanmilikoranglain']=str(hasillahanmilikoranglain[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND status_lahan LIKE '3' ")
			hasillahantanahnegara=cur.fetchone()
			session['lahantanahnegara']=str(hasillahantanahnegara[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND status_lahan LIKE '4' ")
			hasillahanlainnya=cur.fetchone()
			session['lahanlainnya']=str(hasillahanlainnya[0])

			#HITUNG JENIS LANTAI
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_lantai_terluas LIKE '1' ")
			hasillantaimarmer=cur.fetchone()
			session['lantaimarmer']=str(hasillantaimarmer[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_lantai_terluas LIKE '2' ")
			hasillantaikeramik=cur.fetchone()
			session['lantaikeramik']=str(hasillantaikeramik[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_lantai_terluas LIKE '3' ")
			hasillantaiparket=cur.fetchone()
			session['lantaiparket']=str(hasillantaiparket[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_lantai_terluas LIKE '4' ")
			hasillantaiubin=cur.fetchone()
			session['lantaiubin']=str(hasillantaiubin[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_lantai_terluas LIKE '5' ")
			hasillantaikayukualitastinggi=cur.fetchone()
			session['lantaikayubagus']=str(hasillantaikayukualitastinggi[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_lantai_terluas LIKE '6' ")
			hasillantaisemen=cur.fetchone()
			session['lantaisemen']=str(hasillantaisemen[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_lantai_terluas LIKE '7' ")
			hasillantaibambu=cur.fetchone()
			session['lantaibambu']=str(hasillantaibambu[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_lantai_terluas LIKE '8' ")
			hasillantaikayukualitasrendah=cur.fetchone()
			session['lantaikayujelek']=str(hasillantaikayukualitasrendah[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_lantai_terluas LIKE '9' ")
			hasillantaitanah=cur.fetchone()
			session['lantaitanah']=str(hasillantaitanah[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_lantai_terluas LIKE '10' ")
			hasiljenislantailainnya=cur.fetchone()
			session['lantaiembuh']=str(hasiljenislantailainnya[0])

			#HITUNG JUMLAH JENIS DINDING
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_dinding_terluas LIKE '1' ")
			hasiljumlahdindingtembok=cur.fetchone()
			session['jumlahdindingtembok']=str(hasiljumlahdindingtembok[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_dinding_terluas LIKE '2' ")
			hasiljumlahdindingplesterananyaman=cur.fetchone()
			session['jumlahdindingplesterananyaman']=str(hasiljumlahdindingplesterananyaman[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_dinding_terluas LIKE '3' ")
			hasiljumlahdindingkayu=cur.fetchone()
			session['jumlahdindingkayu']=str(hasiljumlahdindingkayu[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_dinding_terluas LIKE '4' ")
			hasiljumlahdindinganyaman=cur.fetchone()
			session['jumlahdindinganyaman']=str(hasiljumlahdindinganyaman[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_dinding_terluas LIKE '5' ")
			hasiljumlahdindingbatangkayu=cur.fetchone()
			session['jumlahdindingbatangkayu']=str(hasiljumlahdindingbatangkayu[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_dinding_terluas LIKE '6' ")
			hasiljumlahdindingbambu=cur.fetchone()
			session['jumlahdindingbambu']=str(hasiljumlahdindingbambu[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_dinding_terluas LIKE '7' ")
			hasiljumlahdindinglainnya=cur.fetchone()
			session['jumlahdindinglainnya']=str(hasiljumlahdindinglainnya[0])

			#HITUNG JUMLAH DINDING DENGAN KUALITAS BAIK
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_dinding_terluas LIKE '1' AND kualitas_dinding123 LIKE '1' ")
			hasiltembokbagus=cur.fetchone()
			session['dindingtembokbagus']=str(hasiltembokbagus[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_dinding_terluas LIKE '2' AND kualitas_dinding123 LIKE '1' ")
			hasilplesterananyamanbagus=cur.fetchone()
			session['dindingplesterananyamanbagus']=str(hasilplesterananyamanbagus[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_dinding_terluas LIKE '3' AND kualitas_dinding123 LIKE '1' ")
			hasiltembokkayubagus=cur.fetchone()
			session['dindingkayubagus']=str(hasiltembokkayubagus[0])

			#HITUNG JUMLAH DINDING DENGAN KUALITAS JELEK
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_dinding_terluas LIKE '1' AND kualitas_dinding123 LIKE '2' ")
			hasiltembokjelek=cur.fetchone()
			session['dindingtembokjelek']=str(hasiltembokjelek[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_dinding_terluas LIKE '2' AND kualitas_dinding123 LIKE '2' ")
			hasilplesterananyamanjelek=cur.fetchone()
			session['dindingplesterananyamanjelek']=str(hasilplesterananyamanjelek[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_dinding_terluas LIKE '3' AND kualitas_dinding123 LIKE '2' ")
			hasiltembokkayujelek=cur.fetchone()
			session['dindingkayujelek']=str(hasiltembokkayujelek[0])

			#HITUNG JENIS ATAP
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '1' ")
			hasilatapgentengbeton=cur.fetchone()
			session['atapgentengbeton']=str(hasilatapgentengbeton[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '2' ")
			hasilatapgentengkeramik=cur.fetchone()
			session['atapgentengkeramik']=str(hasilatapgentengkeramik[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '3' ")
			hasilatapgentengmetal=cur.fetchone()
			session['atapgentengmetal']=str(hasilatapgentengmetal[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '4' ")
			hasilatapgentengtanahliat=cur.fetchone()
			session['atapgentengtanahliat']=str(hasilatapgentengtanahliat[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '5' ")
			hasilatapasbes=cur.fetchone()
			session['atapasbes']=str(hasilatapasbes[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '6' ")
			hasilatapseng=cur.fetchone()
			session['atapseng']=str(hasilatapseng[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '7' ")
			hasilatapsirap=cur.fetchone()
			session['atapsirap']=str(hasilatapsirap[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '8' ")
			hasilatapbambu=cur.fetchone()
			session['atapbambu']=str(hasilatapbambu[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '9' ")
			hasilatapjeramiijukdaundaunanrumbia=cur.fetchone()
			session['atapjeramiijukdaundaunanrumbia']=str(hasilatapjeramiijukdaundaunanrumbia[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '10' ")
			hasilataplainnya=cur.fetchone()
			session['ataplainnya']=str(hasilataplainnya[0])

			#HITUNG JUMLAH ATAP DENGAN KUALITAS JOS
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '1' AND kondisi_atap1234567 LIKE '1' ")
			atapgentengbetonkondisibagus=cur.fetchone()
			session['gentengbetonkondisibagus']=str(atapgentengbetonkondisibagus[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '2' AND kondisi_atap1234567 LIKE '1' ")
			atapgentengkeramikkondisibagus=cur.fetchone()
			session['gentengkeramikkondisibagus']=str(atapgentengkeramikkondisibagus[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '3' AND kondisi_atap1234567 LIKE '1' ")
			atapgentengmetalkondisibagus=cur.fetchone()
			session['gentengmetalkondisibagus']=str(atapgentengmetalkondisibagus[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '4' AND kondisi_atap1234567 LIKE '1' ")
			atapgentengtanahliatkondisibagus=cur.fetchone()
			session['gentengtanahliatkondisibagus']=str(atapgentengtanahliatkondisibagus[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '5' AND kondisi_atap1234567 LIKE '1' ")
			atapasbeskondisibagus=cur.fetchone()
			session['asbeskondisibagus']=str(atapasbeskondisibagus[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '6' AND kondisi_atap1234567 LIKE '1' ")
			atapsengkondisibagus=cur.fetchone()
			session['sengkondisibagus']=str(atapsengkondisibagus[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '7' AND kondisi_atap1234567 LIKE '1' ")
			atapsirapkondisibagus=cur.fetchone()
			session['sirapkondisibagus']=str(atapsirapkondisibagus[0])

			#HITUNG JUMLAH ATAP DENGAN KUALITAS BOBROK
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '1' AND kondisi_atap1234567 LIKE '2' ")
			atapgentengbetonkondisibobrok=cur.fetchone()
			session['gentengbetonkondisibobrok']=str(atapgentengbetonkondisibobrok[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '2' AND kondisi_atap1234567 LIKE '2' ")
			atapgentengkeramikkondisibobrok=cur.fetchone()
			session['gentengkeramikkondisibobrok']=str(atapgentengkeramikkondisibobrok[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '3' AND kondisi_atap1234567 LIKE '2' ")
			atapgentengmetalkondisibobrok=cur.fetchone()
			session['gentengmetalkondisibobrok']=str(atapgentengmetalkondisibobrok[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '4' AND kondisi_atap1234567 LIKE '2' ")
			atapgentengtanahliatkondisibobrok=cur.fetchone()
			session['gentengtanahliatkondisibobrok']=str(atapgentengtanahliatkondisibobrok[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '5' AND kondisi_atap1234567 LIKE '2' ")
			atapasbeskondisibobrok=cur.fetchone()
			session['asbeskondisibobrok']=str(atapasbeskondisibobrok[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '6' AND kondisi_atap1234567 LIKE '2' ")
			atapsengkondisibobrok=cur.fetchone()
			session['sengkondisibobrok']=str(atapsengkondisibobrok[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_atap_terluas LIKE '7' AND kondisi_atap1234567 LIKE '2' ")
			atapsirapkondisibobrok=cur.fetchone()
			session['sirapkondisibobrok']=str(atapsirapkondisibobrok[0])
			return render_template('baru/statistikperumahan.html')
		return redirect(url_for('index'))
	return redirect(url_for('index'))

@appdesa.route('/statistiksanitasi')
def statistiksanitasi():
	if 'pengguna' in session:
		if session['pemerintah']=='desa':

			#MENGHITUNG SUMBER AIR SUDEKAT
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '1' ")
			hasiljumlahairkemasanbermerk=cur.fetchone()
			session['jumlahairkemasanbermerk']=str(hasiljumlahairkemasanbermerk[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '2' ")
			hasiljumlahairisiulang=cur.fetchone()
			session['jumlahairisiulang']=str(hasiljumlahairisiulang[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '3' ")
			hasiljumlahairledingmeteran=cur.fetchone()
			session['jumlahairledingmeteran']=str(hasiljumlahairledingmeteran[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '4' ")
			hasiljumlahairledingeceran=cur.fetchone()
			session['jumlahairledingeceran']=str(hasiljumlahairledingeceran[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '5' ")
			hasiljumlahairsumurborpompa=cur.fetchone()
			session['jumlahairsumurborpompa']=str(hasiljumlahairsumurborpompa[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '6' ")
			hasiljumlahairsumurterlindung=cur.fetchone()
			session['jumlahairsumurterlindung']=str(hasiljumlahairsumurterlindung[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '7' ")
			hasiljumlahairsumurtakterlindung=cur.fetchone()
			session['jumlahairsumurtakterlindung']=str(hasiljumlahairsumurtakterlindung[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '8' ")
			hasiljumlahairmataairterlindung=cur.fetchone()
			session['jumlahairmataairterlindung']=str(hasiljumlahairmataairterlindung[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '9' ")
			hasiljumlahairmataairtakterlindung=cur.fetchone()
			session['jumlahairmataairtakterlindung']=str(hasiljumlahairmataairtakterlindung[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '10' ")
			hasiljumlahairsungaidanauwaduk=cur.fetchone()
			session['jumlahairsungaidanauwaduk']=str(hasiljumlahairsungaidanauwaduk[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '11' ")
			hasiljumlahairhujan=cur.fetchone()
			session['jumlahairhujan']=str(hasiljumlahairhujan[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '12' ")
			hasiljumlahairlainnya=cur.fetchone()
			session['jumlahairlainnya']=str(hasiljumlahairlainnya[0])

			#MENGHITUNG SUMBER AIR BELI NGECER BOS
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '1' AND cara_memperloleh_air_minum LIKE '1' ")
			hasiljumlahairkemasanbermerkeceran=cur.fetchone()
			session['jumlahairkemasanbermerkngecer']=str(hasiljumlahairkemasanbermerkeceran[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '2' AND cara_memperloleh_air_minum LIKE '1' ")
			hasiljumlahairisiulangeceran=cur.fetchone()
			session['jumlahairisiulangngecer']=str(hasiljumlahairisiulangeceran[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '3' AND cara_memperloleh_air_minum LIKE '1' ")
			hasiljumlahairledingmeteraneceran=cur.fetchone()
			session['jumlahairledingmeteraneceran']=str(hasiljumlahairledingmeteraneceran[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '4' AND cara_memperloleh_air_minum LIKE '1' ")
			hasiljumlahairledingeceraneceran=cur.fetchone()
			session['jumlahairledingeceraneceran']=str(hasiljumlahairledingeceraneceran[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '5' AND cara_memperloleh_air_minum LIKE '1' ")
			hasiljumlahairsumurborpompaeceran=cur.fetchone()
			session['jumlahairsumurborpompaeceran']=str(hasiljumlahairsumurborpompaeceran[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '6' AND cara_memperloleh_air_minum LIKE '1' ")
			hasiljumlahairsumurterlindungeceran=cur.fetchone()
			session['jumlahairsumurterlindungeceran']=str(hasiljumlahairsumurterlindungeceran[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '7' AND cara_memperloleh_air_minum LIKE '1' ")
			hasiljumlahairsumurtakterlindungeceran=cur.fetchone()
			session['jumlahairsumurtakterlindungeceran']=str(hasiljumlahairsumurtakterlindungeceran[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '8' AND cara_memperloleh_air_minum LIKE '1' ")
			hasiljumlahairmataairterlindungeceran=cur.fetchone()
			session['jumlahairmataairterlindungeceran']=str(hasiljumlahairmataairterlindungeceran[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '9' AND cara_memperloleh_air_minum LIKE '1' ")
			hasiljumlahairmataairtakterlindungeceran=cur.fetchone()
			session['jumlahairmataairtakterlindungeceran']=str(hasiljumlahairmataairtakterlindungeceran[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '10' AND cara_memperloleh_air_minum LIKE '1' ")
			hasiljumlahairsungaidanauwadukeceran=cur.fetchone()
			session['jumlahairsungaidanauwadukeceran']=str(hasiljumlahairsungaidanauwadukeceran[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '11' AND cara_memperloleh_air_minum LIKE '1' ")
			hasiljumlahairhujaneceran=cur.fetchone()
			session['jumlahairhujaneceran']=str(hasiljumlahairhujaneceran[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '12' AND cara_memperloleh_air_minum LIKE '1' ")
			hasiljumlahairlainnyaeceran=cur.fetchone()
			session['jumlahairlainnyaeceran']=str(hasiljumlahairlainnyaeceran[0])

			#MENGHITUNG SUMBER AIR BELI BERLANGGANAN
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '1' AND cara_memperloleh_air_minum LIKE '2' ")
			hasiljumlahairkemasanbermerklangganan=cur.fetchone()
			session['jumlahairkemasanbermerklangganan']=str(hasiljumlahairkemasanbermerklangganan[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '2' AND cara_memperloleh_air_minum LIKE '2' ")
			hasiljumlahairisiulanglangganan=cur.fetchone()
			session['jumlahairisiulanglangganan']=str(hasiljumlahairisiulanglangganan[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '3' AND cara_memperloleh_air_minum LIKE '2' ")
			hasiljumlahairledingmeteranlangganan=cur.fetchone()
			session['jumlahairledingmeteranlangganan']=str(hasiljumlahairledingmeteranlangganan[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '4' AND cara_memperloleh_air_minum LIKE '2' ")
			hasiljumlahairledingeceranlangganan=cur.fetchone()
			session['jumlahairledingeceranlangganan']=str(hasiljumlahairledingeceranlangganan[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '5' AND cara_memperloleh_air_minum LIKE '2' ")
			hasiljumlahairsumurborpompalangganan=cur.fetchone()
			session['jumlahairsumurborpompalangganan']=str(hasiljumlahairsumurborpompalangganan[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '6' AND cara_memperloleh_air_minum LIKE '2' ")
			hasiljumlahairsumurterlindunglangganan=cur.fetchone()
			session['jumlahairsumurterlindunglangganan']=str(hasiljumlahairsumurterlindunglangganan[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '7' AND cara_memperloleh_air_minum LIKE '2' ")
			hasiljumlahairsumurtakterlindunglangganan=cur.fetchone()
			session['jumlahairsumurtakterlindunglangganan']=str(hasiljumlahairsumurtakterlindunglangganan[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '8' AND cara_memperloleh_air_minum LIKE '2' ")
			hasiljumlahairmataairterlindunglangganan=cur.fetchone()
			session['jumlahairmataairterlindunglangganan']=str(hasiljumlahairmataairterlindunglangganan[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '9' AND cara_memperloleh_air_minum LIKE '2' ")
			hasiljumlahairmataairtakterlindunglangganan=cur.fetchone()
			session['jumlahairmataairtakterlindunglangganan']=str(hasiljumlahairmataairtakterlindunglangganan[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '10' AND cara_memperloleh_air_minum LIKE '2' ")
			hasiljumlahairsungaidanauwaduklangganan=cur.fetchone()
			session['jumlahairsungaidanauwaduklangganan']=str(hasiljumlahairsungaidanauwaduklangganan[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '11' AND cara_memperloleh_air_minum LIKE '2' ")
			hasiljumlahairhujanlangganan=cur.fetchone()
			session['jumlahairhujanlangganan']=str(hasiljumlahairhujanlangganan[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '12' AND cara_memperloleh_air_minum LIKE '2' ")
			hasiljumlahairlainnyalangganan=cur.fetchone()
			session['jumlahairlainnyalangganan']=str(hasiljumlahairlainnyalangganan[0])

			#MENGHITUNG SUMBER AIR TYDAC BELI
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '1' AND cara_memperloleh_air_minum LIKE '3' ")
			hasiljumlahairkemasanbermerktidakbeli=cur.fetchone()
			session['jumlahairkemasanbermerktidakbeli']=str(hasiljumlahairkemasanbermerktidakbeli[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '2' AND cara_memperloleh_air_minum LIKE '3' ")
			hasiljumlahairisiulangtidakbeli=cur.fetchone()
			session['jumlahairisiulangtidakbeli']=str(hasiljumlahairisiulangtidakbeli[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '3' AND cara_memperloleh_air_minum LIKE '3' ")
			hasiljumlahairledingmeterantidakbeli=cur.fetchone()
			session['jumlahairledingmeterantidakbeli']=str(hasiljumlahairledingmeterantidakbeli[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '4' AND cara_memperloleh_air_minum LIKE '3' ")
			hasiljumlahairledingecerantidakbeli=cur.fetchone()
			session['jumlahairledingecerantidakbeli']=str(hasiljumlahairledingecerantidakbeli[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '5' AND cara_memperloleh_air_minum LIKE '3' ")
			hasiljumlahairsumurborpompatidakbeli=cur.fetchone()
			session['jumlahairsumurborpompatidakbeli']=str(hasiljumlahairsumurborpompatidakbeli[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '6' AND cara_memperloleh_air_minum LIKE '3' ")
			hasiljumlahairsumurterlindungtidakbeli=cur.fetchone()
			session['jumlahairsumurterlindungtidakbeli']=str(hasiljumlahairsumurterlindungtidakbeli[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '7' AND cara_memperloleh_air_minum LIKE '3' ")
			hasiljumlahairsumurtakterlindungtidakbeli=cur.fetchone()
			session['jumlahairsumurtakterlindungtidakbeli']=str(hasiljumlahairsumurtakterlindungtidakbeli[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '8' AND cara_memperloleh_air_minum LIKE '3' ")
			hasiljumlahairmataairterlindungtidakbeli=cur.fetchone()
			session['jumlahairmataairterlindungtidakbeli']=str(hasiljumlahairmataairterlindungtidakbeli[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '9' AND cara_memperloleh_air_minum LIKE '3' ")
			hasiljumlahairmataairtakterlindungtidakbeli=cur.fetchone()
			session['jumlahairmataairtakterlindungtidakbeli']=str(hasiljumlahairmataairtakterlindungtidakbeli[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '10' AND cara_memperloleh_air_minum LIKE '3' ")
			hasiljumlahairsungaidanauwaduktidakbeli=cur.fetchone()
			session['jumlahairsungaidanauwaduktidakbeli']=str(hasiljumlahairsungaidanauwaduktidakbeli[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '11' AND cara_memperloleh_air_minum LIKE '3' ")
			hasiljumlahairhujantidakbeli=cur.fetchone()
			session['jumlahairhujantidakbeli']=str(hasiljumlahairhujantidakbeli[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_air_minum LIKE '12' AND cara_memperloleh_air_minum LIKE '3' ")
			hasiljumlahairlainnyatidakbeli=cur.fetchone()
			session['jumlahairlainnyatidakbeli']=str(hasiljumlahairlainnyatidakbeli[0])

			#MENGHITUNG FASILITAS BAB
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND fasilitas_bab LIKE '1' ")
			hasilfasilitasbabsendiri=cur.fetchone()
			session['babsendiri']=str(hasilfasilitasbabsendiri[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND fasilitas_bab LIKE '2' ")
			hasilfasilitasbabumum=cur.fetchone()
			session['babumum']=str(hasilfasilitasbabumum[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND fasilitas_bab LIKE '3' ")
			hasilfasilitasbabbersama=cur.fetchone()
			session['babbersama']=str(hasilfasilitasbabbersama[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND fasilitas_bab LIKE '4' ")
			hasilfasilitasbabtidakada=cur.fetchone()
			session['babtidakada']=str(hasilfasilitasbabtidakada[0])

			#MENGHITUNG JENIS KLOSET
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_kloset LIKE '1' ")
			hasilklosetleherangsa=cur.fetchone()
			session['klosetleherangsa']=str(hasilklosetleherangsa[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_kloset LIKE '2' ")
			hasilklosetplengsengan=cur.fetchone()
			session['klosetplengsengan']=str(hasilklosetplengsengan[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_kloset LIKE '3' ")
			hasilklosetcemplung=cur.fetchone()
			session['klosetcemplung']=str(hasilklosetcemplung[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_kloset LIKE '4' ")
			hasilklosettidakpakai=cur.fetchone()
			session['klosettidakpakai']=str(hasilklosettidakpakai[0])

			#MENGHITUNG TPA TINJA
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND tpa_tinja LIKE '1' ")
			hasiltpatinjatangki=cur.fetchone()
			session['tpatinjatangki']=str(hasiltpatinjatangki[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND tpa_tinja LIKE '2' ")
			hasiltpatinjaspal=cur.fetchone()
			session['tpatinjaspal']=str(hasiltpatinjaspal[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND tpa_tinja LIKE '3' ")
			hasiltpatinjalubangtanah=cur.fetchone()
			session['tpatinjalubangtanah']=str(hasiltpatinjalubangtanah[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND tpa_tinja LIKE '4' ")
			hasiltpatinjakolamsawahsungaidanaulaut=cur.fetchone()
			session['tpatinjakolamsawahsungaidanaulaut']=str(hasiltpatinjakolamsawahsungaidanaulaut[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND tpa_tinja LIKE '5' ")
			hasiltpatinjapantaitanahlapangkebun=cur.fetchone()
			session['tpatinjapantaitanahlapangkebun']=str(hasiltpatinjapantaitanahlapangkebun[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND tpa_tinja LIKE '6' ")
			hasiltpatinjalainnya=cur.fetchone()
			session['tpatinjalainnya']=str(hasiltpatinjalainnya[0])
			return render_template('baru/statistiksanitasi.html')
		return redirect(url_for('index'))
	return redirect(url_for('index'))

#STATISTIK PENERANGAN
@appdesa.route('/statistikpenerangan')
def statistikpenerangan():
	if 'pengguna' in session:
		if session['pemerintah']=='desa':

			#MENGHITUNG JUMLAH PENERANGAN 
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_penerangan LIKE '1' ")
			hasillistrikpln=cur.fetchone()
			session['listrikpln']=str(hasillistrikpln[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_penerangan LIKE '2' ")
			hasillistriknonpln=cur.fetchone()
			session['listriknonpln']=str(hasillistriknonpln[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_penerangan LIKE '3' ")
			hasilbukanlistrik=cur.fetchone()
			session['bukanlistrik']=str(hasilbukanlistrik[0])

			#MENGHITUNG DAYA LISTRIK
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_penerangan LIKE '1' AND daya_listrik LIKE '1' ")
			hasillistrik450watt=cur.fetchone()
			session['listrik450watt']=str(hasillistrik450watt[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_penerangan LIKE '1' AND daya_listrik LIKE '2' ")
			hasillistrik900watt=cur.fetchone()
			session['listrik900watt']=str(hasillistrik900watt[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_penerangan LIKE '1' AND daya_listrik LIKE '3' ")
			hasillistrik1300watt=cur.fetchone()
			session['listrik1300watt']=str(hasillistrik1300watt[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_penerangan LIKE '1' AND daya_listrik LIKE '4' ")
			hasillistrik2200watt=cur.fetchone()
			session['listrik2200watt']=str(hasillistrik2200watt[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_penerangan LIKE '1' AND daya_listrik LIKE '5' ")
			hasillistriklebihdari2200watt=cur.fetchone()
			session['listriklebihdari2200watt']=str(hasillistriklebihdari2200watt[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sumber_penerangan LIKE '1' AND daya_listrik LIKE '6' ")
			hasillistriktanpameteran=cur.fetchone()
			session['listriktanpameteran']=str(hasillistriktanpameteran[0])
			return render_template('baru/statistikpenerangan.html')
		return redirect(url_for('index'))
	return redirect(url_for('index'))

#STATISTIK BAHAN BAKAR MASAK
@appdesa.route('/statistikbahanbakarmasak')
def statistikbahanbakarmasak():
	if 'pengguna' in session:
		if session['pemerintah']=='desa':

			#MENGHITUNG JUMLAH BAHAN BAKAR MASAK
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND bahan_bakar_masak LIKE '1' ")
			hasilbahanbakarmasaklistrik=cur.fetchone()
			session['bahanbakarmasaklistrik']=str(hasilbahanbakarmasaklistrik[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND bahan_bakar_masak LIKE '2' ")
			hasilbahanbakarmasakgaslebihdari3kg=cur.fetchone()
			session['bahanbakarmasakgaslebihdari3kg']=str(hasilbahanbakarmasakgaslebihdari3kg[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND bahan_bakar_masak LIKE '3' ")
			hasilbahanbakarmasakgas3kg=cur.fetchone()
			session['bahanbakarmasakgas3kg']=str(hasilbahanbakarmasakgas3kg[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND bahan_bakar_masak LIKE '3' ")
			hasilbahanbakarmasakbiogas=cur.fetchone()
			session['bahanbakarmasakbiogas']=str(hasilbahanbakarmasakbiogas[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND bahan_bakar_masak LIKE '4' ")
			hasilbahanbakarmasakminyaktanah=cur.fetchone()
			session['bahanbakarmasakminyaktanah']=str(hasilbahanbakarmasakminyaktanah[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND bahan_bakar_masak LIKE '5' ")
			hasilbahanbakarmasakbriket=cur.fetchone()
			session['bahanbakarmasakbriket']=str(hasilbahanbakarmasakbriket[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND bahan_bakar_masak LIKE '6' ")
			hasilbahanbakarmasakarang=cur.fetchone()
			session['bahanbakarmasakarang']=str(hasilbahanbakarmasakarang[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND bahan_bakar_masak LIKE '7' ")
			hasilbahanbakarmasakkayubakar=cur.fetchone()
			session['bahanbakarmasakkayubakar']=str(hasilbahanbakarmasakkayubakar[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND bahan_bakar_masak LIKE '8' ")
			hasiltidakmemasakdirumah=cur.fetchone()
			session['tidakmemasakdirumah']=str(hasiltidakmemasakdirumah[0])
			return render_template('baru/statistikbahanbakarmasak.html')
		return redirect(url_for('index'))
	return redirect(url_for('index'))

#STATISTIK KEPEMILIKAN ASET
@appdesa.route('/statistikkepemilikanaset')
def statistikkepemilikanaset():
	if 'pengguna' in session:
		if session['pemerintah']=='desa':

			#MENGHITUNG JUMLAH KEPEMILIKAN ASET BERGERAK
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND tabung_gas_5_5kg_lebih LIKE '1' ")
			jumlahpunyatabunggas5kglebih=cur.fetchone()
			session['tabunggas5kglebih']=str(jumlahpunyatabunggas5kglebih[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND kulkas LIKE '3' ")
			jumlahpunyakulkas=cur.fetchone()
			session['punyakulkas']=str(jumlahpunyakulkas[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND ac LIKE '1' ")
			jumlahpunyaac=cur.fetchone()
			session['punyaac']=str(jumlahpunyaac[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND pemanas_air LIKE '3' ")
			jumlahpunyapemanasair=cur.fetchone()
			session['punyapemanasair']=str(jumlahpunyapemanasair[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND telp_rumah LIKE '1' ")
			jumlahpunyatelponrumah=cur.fetchone()
			session['punyatelponrumah']=str(jumlahpunyatelponrumah[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND televisi LIKE '3' ")
			jumlahpunyatelevisi=cur.fetchone()
			session['punyatelevisi']=str(jumlahpunyatelevisi[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND emas_perhiasan_tabungan LIKE '1' ")
			jumlahpunyaemasperhiasantabungan=cur.fetchone()
			session['punyaemasperhiasantabungan']=str(jumlahpunyaemasperhiasantabungan[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND komputer LIKE '3' ")
			jumlahpunyakomputer=cur.fetchone()
			session['punyakomputer']=str(jumlahpunyakomputer[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sepeda LIKE '1' ")
			jumlahpunyasepeda=cur.fetchone()
			session['punyasepeda']=str(jumlahpunyasepeda[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sepeda_motor LIKE '3' ")
			jumlahpunyasepedamotor=cur.fetchone()
			session['punyasepedamotor']=str(jumlahpunyasepedamotor[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND mobil LIKE '1' ")
			jumlahpunyamobil=cur.fetchone()
			session['punyamobil']=str(jumlahpunyamobil[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND perahu LIKE '3' ")
			jumlahpunyaperahu=cur.fetchone()
			session['punyaperahu']=str(jumlahpunyaperahu[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND motor_tempel LIKE '1' ")
			jumlahpunyamotortempel=cur.fetchone()
			session['punyamotortempel']=str(jumlahpunyamotortempel[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND perahu_motor LIKE '3' ")
			jumlahpunyaperahumotor=cur.fetchone()
			session['punyaperahumotor']=str(jumlahpunyaperahumotor[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND kapal LIKE '1' ")
			jumlahpunyakapal=cur.fetchone()
			session['punyakapal']=str(jumlahpunyakapal[0])

			#MENGHITUNG JUMLAH KEPEMILIKAN ASET TIDAK BERGERAK
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND aset_lahan LIKE '1' ")
			jumlahpunyaasetlahan=cur.fetchone()
			session['punyaasetlahan']=str(jumlahpunyaasetlahan[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND rumah_ditempat_lain LIKE '3' ")
			jumlahpunyarumahditempatlain=cur.fetchone()
			session['punyarumahditempatlain']=str(jumlahpunyarumahditempatlain[0])

			#MENGHITUNG JUMLAH KEPEMILIKAN TERNAK
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jumlah_sapi>=1 ")
			jumlahpunyasapi=cur.fetchone()
			session['punyasapi']=str(jumlahpunyasapi[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jumlah_kerbau>=1 ")
			jumlahpunyakerbau=cur.fetchone()
			session['punyakerbau']=str(jumlahpunyakerbau[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jumlah_kuda>=1 ")
			jumlahpunyakuda=cur.fetchone()
			session['punyakuda']=str(jumlahpunyakuda[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jumlah_babi>=1 ")
			jumlahpunyababi=cur.fetchone()
			session['punyababi']=str(jumlahpunyababi[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jumlah_kambing_domba>=1 ")
			jumlahpunyakambingdomba=cur.fetchone()
			session['punyakambingdomba']=str(jumlahpunyakambingdomba[0])

			return render_template('baru/statistikkepemilikanaset.html')
		return redirect(url_for('index'))
	return redirect(url_for('index'))

#STATISTIK KEIKUTSERTAAN PROGRAM
@appdesa.route('/statistikkeikutsertaanprogram')
def statistikkeikutsertaanprogram():
	if 'pengguna' in session:
		if session['pemerintah']=='desa':

			#MENGHITUNG JUMLAH KEIKUTSERTAAN PROGRAM
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND kks_kps LIKE '1' ")
			jumlahikutkkskps=cur.fetchone()
			session['ikutkkskps']=str(jumlahikutkkskps[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND bip_bsm LIKE '3' ")
			jumlahikutbipbsm=cur.fetchone()
			session['ikutbipbsm']=str(jumlahikutbipbsm[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND kis_bpjs_jamkesmas LIKE '1' ")
			jumlahikutksbpjsjamkesmas=cur.fetchone()
			session['ikutksbpjsjamkesmas']=str(jumlahikutksbpjsjamkesmas[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND bpjs_mandiri LIKE '3' ")
			jumlahikutbpjsmandiri=cur.fetchone()
			session['ikutbpjsmandiri']=str(jumlahikutbpjsmandiri[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jamsostek_bpjs_ketenagakerjaan LIKE '1' ")
			jumlahikutjamsostekbpjsketenagakerjaan=cur.fetchone()
			session['ikutjamsostekbpjsketenagakerjaan']=str(jumlahikutjamsostekbpjsketenagakerjaan[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND asuransi_kesehatan_lainnya LIKE '3' ")
			jumlahikutasuransikesehatanlainnya=cur.fetchone()
			session['ikutasuransikesehatanlainnya']=str(jumlahikutasuransikesehatanlainnya[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND pkh LIKE '1' ")
			jumlahikutpkh=cur.fetchone()
			session['ikutpkh']=str(jumlahikutpkh[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND kur LIKE '1' ")
			jumlahikutkur=cur.fetchone()
			session['ikutkur']=str(jumlahikutkur[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_kemiskinan-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND raskin LIKE '3' ")
			jumlahikutraskin=cur.fetchone()
			session['ikutraskin']=str(jumlahikutraskin[0])

			return render_template('baru/statistikkeikutsertaanprogram.html')
		return redirect(url_for('index'))
	return redirect(url_for('index'))

#STATISTIK KEPEMILIKAN KARTU IDENTITAS
@appdesa.route('/statistikkepemilikankartuidentitas')
def statistikkepemilikankartuidentitas():
	if 'pengguna' in session:
		if session['pemerintah']=='desa':

			#MENGHITUNG JUMLAH KEPEMILIKAN KARTU IDENTITAS
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND akta_kelahiran LIKE 'Ya' ")
			jumlahpunyaaktakelahiran=cur.fetchone()
			session['punyaaktakelahiran']=str(jumlahpunyaaktakelahiran[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND kartu_pelajar LIKE 'Ya' ")
			jumlahpunyakartupelajar=cur.fetchone()
			session['punyakartupelajar']=str(jumlahpunyakartupelajar[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND ktp LIKE 'Ya' ")
			jumlahpunyaktp=cur.fetchone()
			session['punyaktp']=str(jumlahpunyaktp[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND sim LIKE 'Ya' ")
			jumlahpunyasim=cur.fetchone()
			session['punyasim']=str(jumlahpunyasim[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND tidak_memiliki_kartu_identitas LIKE 'Ya' ")
			jumlahtidakpunyaidentitas=cur.fetchone()
			session['tidakpunyaidentitas']=str(jumlahtidakpunyaidentitas[0])

			return render_template('baru/statistik_kepemilikan_kartu_identitas.html')
		return redirect(url_for('index'))
	return redirect(url_for('index'))


#STATISTIK DISABILITAS
@appdesa.route('/disabilitas')
def disabilitas():
	if 'pengguna' in session:
		if session['pemerintah']=='desa':

			#MENGHITUNG JUMLAH PENYANDANG DISABILITAS
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_cacat LIKE '0' ")
			jumlahtidakcacat=cur.fetchone()
			session['tidakcacat']=str(jumlahtidakcacat[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_cacat LIKE '1' ")
			jumlahtunadaksa=cur.fetchone()
			session['tunadaksa']=str(jumlahtunadaksa[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_cacat LIKE '2' ")
			jumlahtunanetra=cur.fetchone()
			session['tunanetra']=str(jumlahtunanetra[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_cacat LIKE '3' ")
			jumlahtunarungu=cur.fetchone()
			session['tunarungu']=str(jumlahtunarungu[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_cacat LIKE '4' ")
			jumlahtunawicara=cur.fetchone()
			session['tunawicara']=str(jumlahtunawicara[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_cacat LIKE '5' ")
			jumlahtunarunguwicara=cur.fetchone()
			session['tunarunguwicara']=str(jumlahtunarunguwicara[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_cacat LIKE '6' ")
			jumlahtunanetracacattubuh=cur.fetchone()
			session['tunanetracacattubuh']=str(jumlahtunanetracacattubuh[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_cacat LIKE '7' ")
			jumlahtunanetrarunguwicara=cur.fetchone()
			session['tunanetrarunguwicara']=str(jumlahtunanetrarunguwicara[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_cacat LIKE '8' ")
			jumlahtunarunguwicaracacattubuh=cur.fetchone()
			session['tunarunguwicaracacattubuh']=str(jumlahtunarunguwicaracacattubuh[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_cacat LIKE '9' ")
			jumlahtunarunguwicaranetracacattubuh=cur.fetchone()
			session['tunarunguwicaranetracacattubuh']=str(jumlahtunarunguwicaranetracacattubuh[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_cacat LIKE '10' ")
			jumlahcacatmental=cur.fetchone()
			session['cacatmental']=str(jumlahcacatmental[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_cacat LIKE '11' ")
			jumlahmantanpenderitagangguanjiwa=cur.fetchone()
			session['mantanpenderitagangguanjiwa']=str(jumlahmantanpenderitagangguanjiwa[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND jenis_cacat LIKE '12' ")
			jumlahcacatfisik=cur.fetchone()
			session['cacatfisik']=str(jumlahcacatfisik[0])
			return render_template('baru/statistikdisabilitas.html')
		return redirect(url_for('index'))
	return redirect(url_for('index'))


#STATISTIK PENYAKIT KRONIS
@appdesa.route('/penyakitkronis')
def penyakitkronis():
	if 'pengguna' in session:
		if session['pemerintah']=='desa':

			#MENGHITUNG JUMLAH PENDERITA PENYAKIT KRONIS/MENAHUN
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND penyakit_kronis LIKE '0' ")
			jumlahtidakadapenyakit=cur.fetchone()
			session['tidakadapenyakit']=str(jumlahtidakadapenyakit[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND penyakit_kronis LIKE '1' ")
			jumlahpunyakithipertensi=cur.fetchone()
			session['hipertensi']=str(jumlahpunyakithipertensi[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND penyakit_kronis LIKE '2' ")
			jumlahpenyakitrematik=cur.fetchone()
			session['rematik']=str(jumlahpenyakitrematik[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND penyakit_kronis LIKE '3' ")
			jumlahpenyakitasma=cur.fetchone()
			session['asma']=str(jumlahpenyakitasma[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND penyakit_kronis LIKE '4' ")
			jumlahpenyakitjantung=cur.fetchone()
			session['jantung']=str(jumlahpenyakitjantung[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND penyakit_kronis LIKE '5' ")
			jumlahpenyakitdiabetes=cur.fetchone()
			session['diabetes']=str(jumlahpenyakitdiabetes[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND penyakit_kronis LIKE '6' ")
			jumlahpenyakittbc=cur.fetchone()
			session['tbc']=str(jumlahpenyakittbc[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND penyakit_kronis LIKE '7' ")
			jumlahpenyakitstroke=cur.fetchone()
			session['stroke']=str(jumlahpenyakitstroke[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND penyakit_kronis LIKE '8' ")
			jumlahpenyakitkankertumorganas=cur.fetchone()
			session['kankertumorganas']=str(jumlahpenyakitkankertumorganas[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND penyakit_kronis LIKE '9' ")
			jumlahpenyakitlainnya=cur.fetchone()
			session['penyakitlainnya']=str(jumlahpenyakitlainnya[0])
			return render_template('baru/statistikpenyakitkronis.html')
		return redirect(url_for('index'))
	return redirect(url_for('index'))

#STATISTIK PARTISIPASI SEKOLAH
@appdesa.route('/partisipasisekolah')
def partisipasisekolah():
	if 'pengguna' in session:
		if session['pemerintah']=='desa':

			#MENGHITUNG PARTISIPASI SEKOLAH ANGGOTA RUMAH TANGGA UMUR 5 TAHUN KEATAS
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '0' AND umur>=5 ")
			jumlahtidakbelumpernahsekolah=cur.fetchone()
			session['tidakbelumpernahsekolah']=str(jumlahtidakbelumpernahsekolah[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND umur>=5 ")
			jumlahmasihsekolah=cur.fetchone()
			session['masihsekolah']=str(jumlahmasihsekolah[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND umur>=5 ")
			jumlahtidakbersekolahlagi=cur.fetchone()
			session['tidakbersekolahlagi']=str(jumlahtidakbersekolahlagi[0])

			#MENGHITUNG UMUR PARTISIPASI SEKOLAH ANGGOTA RUMAH TANGGA UMUR 5 TAHUN KEATAS BELUM/TIDAK PERNAH BERSEKOLAH
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '0' AND umur IN (5,6,7,8,9,10,11,12,13,14,15,16,16,18,19,20) ")
			jumlahtidakbelumpernahsekolahusia5sampai20tahun=cur.fetchone()
			session['belumpernahsekolahusia5sampai20']=str(jumlahtidakbelumpernahsekolahusia5sampai20tahun[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '0' AND umur IN (21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39) ")
			jumlahtidakbelumpernahsekolahusia21sampai40tahun=cur.fetchone()
			session['belumpernahsekolahusia21sampai40']=str(jumlahtidakbelumpernahsekolahusia21sampai40tahun[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '0' AND umur>=40 ")
			jumlahtidakbelumpernahsekolahusiadiatas40tahun=cur.fetchone()
			session['belumpernahsekolahusiadiatas40']=str(jumlahtidakbelumpernahsekolahusiadiatas40tahun[0])

			#MENGHITUNG UMUR PARTISIPASI SEKOLAH ANGGOTA RUMAH TANGGA UMUR 5 TAHUN KEATAS MASIH BERSEKOLAH
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND umur IN (5,6,7,8,9,10,11,12,13,14,15,16,16,18,19,20) ")
			jumlahmasihsekolahusia5sampai20tahun=cur.fetchone()
			session['masihsekolahusia5sampai20']=str(jumlahmasihsekolahusia5sampai20tahun[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND umur IN (21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39) ")
			jumlahmasihsekolahusia21sampai40tahun=cur.fetchone()
			session['masihsekolahusia21sampai40']=str(jumlahmasihsekolahusia21sampai40tahun[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND umur>=40 ")
			jumlahmasihsekolahusiadiatas40tahun=cur.fetchone()
			session['masihsekolahusiadiatas40']=str(jumlahmasihsekolahusiadiatas40tahun[0])

			#MENGHITUNG UMUR PARTISIPASI SEKOLAH ANGGOTA RUMAH TANGGA UMUR 5 TAHUN KEATAS TIDAK BERSEKOLAH BERSEKOLAH LAGI
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND umur IN (5,6,7,8,9,10,11,12,13,14,15,16,16,18,19,20) ")
			jumlahmtidaksekolahlagiusia5sampai20tahun=cur.fetchone()
			session['tidaksekolahlagiusia5sampai20']=str(jumlahmtidaksekolahlagiusia5sampai20tahun[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND umur IN (21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39) ")
			jumlahtidaksekolahusialagi21sampai40tahun=cur.fetchone()
			session['tidaksekolahlagiusia21sampai40']=str(jumlahtidaksekolahusialagi21sampai40tahun[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND umur>=40 ")
			jumlahtidaksekolahlagiusiadiatas40tahun=cur.fetchone()
			session['tidaksekolahlagiusiadiatas40']=str(jumlahtidaksekolahlagiusiadiatas40tahun[0])

			#MENGHITUNG JENJANG PENDIDIKAN TERTINGGI ANAK YANG MASIH BERSEKOLAH
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_jenjang_pendidikan_tertinggi LIKE '1' ")
			jumlahmasihbersekolahsd=cur.fetchone()
			session['masihsekolahsd']=str(jumlahmasihbersekolahsd[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_jenjang_pendidikan_tertinggi LIKE '2' ")
			jumlahmasihsekolahpaketa=cur.fetchone()
			session['masihsekolahpaketa']=str(jumlahmasihsekolahpaketa[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_jenjang_pendidikan_tertinggi LIKE '3' ")
			jumlahmasihsekolahmibtidaiyah=cur.fetchone()
			session['masihsekolahmibtidaiyah']=str(jumlahmasihsekolahmibtidaiyah[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_jenjang_pendidikan_tertinggi LIKE '4' ")
			jumlahmasihsekolahsmp=cur.fetchone()
			session['masihsekolahsmp']=str(jumlahmasihsekolahsmp[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_jenjang_pendidikan_tertinggi LIKE '5' ")
			jumlahmasihsekolahpaketb=cur.fetchone()
			session['masihsekolahpaketb']=str(jumlahmasihsekolahpaketb[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_jenjang_pendidikan_tertinggi LIKE '6' ")
			jumlahmasihsekolahmtsanawiyah=cur.fetchone()
			session['masihsekolahmtsanawiyah']=str(jumlahmasihsekolahmtsanawiyah[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_jenjang_pendidikan_tertinggi LIKE '7' ")
			jumlahmasihsekolahsma=cur.fetchone()
			session['masihsekolahsma']=str(jumlahmasihsekolahsma[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_jenjang_pendidikan_tertinggi LIKE '8' ")
			jumlahmasihsekolahpaketc=cur.fetchone()
			session['masihsekolahpaketc']=str(jumlahmasihsekolahpaketc[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_jenjang_pendidikan_tertinggi LIKE '9' ")
			jumlahmasihsekolahmaliyah=cur.fetchone()
			session['masihsekolahmaliyah']=str(jumlahmasihsekolahmaliyah[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_jenjang_pendidikan_tertinggi LIKE '10' ")
			jumlahmasihsekolahperguruantinggi=cur.fetchone()
			session['masihsekolahperguruantinggi']=str(jumlahmasihsekolahperguruantinggi[0])

			#MENGHITUNG JENJANG PENDIDIKAN TERTINGGI ANAK YANG TIDAK BERSEKOLAH LAGI
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_jenjang_pendidikan_tertinggi LIKE '1' ")
			jumlahtidaksekolahlagisd=cur.fetchone()
			session['tidaksekolahsd']=str(jumlahtidaksekolahlagisd[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_jenjang_pendidikan_tertinggi LIKE '2' ")
			jumlahtidaksekolahlagipaketa=cur.fetchone()
			session['tidaksekolahpaketa']=str(jumlahtidaksekolahlagipaketa[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_jenjang_pendidikan_tertinggi LIKE '3' ")
			jumlahtidaksekolahlagimibtidaiyah=cur.fetchone()
			session['tidaksekolahmibtidaiyah']=str(jumlahtidaksekolahlagimibtidaiyah[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_jenjang_pendidikan_tertinggi LIKE '4' ")
			jumlahtidaksekolahlagismp=cur.fetchone()
			session['tidaksekolahsmp']=str(jumlahtidaksekolahlagismp[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_jenjang_pendidikan_tertinggi LIKE '5' ")
			jumlahtidaksekolahlagipaketb=cur.fetchone()
			session['tidaksekolahpaketb']=str(jumlahtidaksekolahlagipaketb[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_jenjang_pendidikan_tertinggi LIKE '6' ")
			jumlahtidaksekolahlagimtsanawiyah=cur.fetchone()
			session['tidaksekolahmtsanawiyah']=str(jumlahtidaksekolahlagimtsanawiyah[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_jenjang_pendidikan_tertinggi LIKE '7' ")
			jumlahtidaksekolahlagisma=cur.fetchone()
			session['tidaksekolahsma']=str(jumlahtidaksekolahlagisma[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_jenjang_pendidikan_tertinggi LIKE '8' ")
			jumlahtidaksekolahlagipaketc=cur.fetchone()
			session['tidaksekolahpaketc']=str(jumlahtidaksekolahlagipaketc[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_jenjang_pendidikan_tertinggi LIKE '9' ")
			jumlahtidaksekolahlagimaliyah=cur.fetchone()
			session['tidaksekolahmaliyah']=str(jumlahtidaksekolahlagimaliyah[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_jenjang_pendidikan_tertinggi LIKE '10' ")
			jumlahtidaksekolahlagiperguruantinggi=cur.fetchone()
			session['tidaksekolahperguruantinggi']=str(jumlahtidaksekolahlagiperguruantinggi[0])	

			#MENGHITUNG KELAS TERTINGGI YANG PERNAH DIDUDUKI UNTUK ANAK YANG MASIH BERSEKOLAH
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_kelas_tertinggi LIKE '1' ")
			jumlahmasihkelassatu=cur.fetchone()
			session['masihkelas1']=str(jumlahmasihkelassatu[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_kelas_tertinggi LIKE '2' ")
			jumlahmasihkeladua=cur.fetchone()
			session['masihkelas2']=str(jumlahmasihkeladua[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_kelas_tertinggi LIKE '3' ")
			jumlahmasihkelastiga=cur.fetchone()
			session['masihkelas3']=str(jumlahmasihkelastiga[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_kelas_tertinggi LIKE '4' ")
			jumlahmasihkelasempat=cur.fetchone()
			session['masihkelas4']=str(jumlahmasihkelasempat[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_kelas_tertinggi LIKE '5' ")
			jumlahmasihkelaslima=cur.fetchone()
			session['masihkelas5']=str(jumlahmasihkelaslima[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_kelas_tertinggi LIKE '6' ")
			jumlahmasihkelasenam=cur.fetchone()
			session['masihkelas6']=str(jumlahmasihkelasenam[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_kelas_tertinggi LIKE '7' ")
			jumlahmasihkelastujuh=cur.fetchone()
			session['masihkelas7']=str(jumlahmasihkelastujuh[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_kelas_tertinggi LIKE '8' ")
			jumlahmasihkelasdelapan=cur.fetchone()
			session['masihkelas8']=str(jumlahmasihkelasdelapan[0])


			#MENGHITUNG KELAS TERTINGGI YANG PERNAH DIDUDUKI UNTUK ANAK YANG TIDAK BERSEKOLAH LAGI
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_kelas_tertinggi LIKE '1' ")
			jumlahtidakbersekolahlagikelassatu=cur.fetchone()
			session['tidakbersekolahlagikelas1']=str(jumlahtidakbersekolahlagikelassatu[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_kelas_tertinggi LIKE '2' ")
			jumlahtidakbersekolahlagikelasdua=cur.fetchone()
			session['tidakbersekolahlagikelas2']=str(jumlahtidakbersekolahlagikelasdua[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_kelas_tertinggi LIKE '3' ")
			jumlahtidakbersekolahlagikelastiga=cur.fetchone()
			session['tidakbersekolahlagikelas3']=str(jumlahtidakbersekolahlagikelastiga[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_kelas_tertinggi LIKE '4' ")
			jumlahtidakbersekolahlagikelasempat=cur.fetchone()
			session['tidakbersekolahlagikelas4']=str(jumlahtidakbersekolahlagikelasempat[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_kelas_tertinggi LIKE '5' ")
			jumlahtidakbersekolahlagikelaslima=cur.fetchone()
			session['tidakbersekolahlagikelas5']=str(jumlahtidakbersekolahlagikelaslima[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_kelas_tertinggi LIKE '6' ")
			jumlahtidakbersekolahlagikelasenam=cur.fetchone()
			session['tidakbersekolahlagikelas6']=str(jumlahtidakbersekolahlagikelasenam[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_kelas_tertinggi LIKE '7' ")
			jumlahtidakbersekolahlagikelastujuh=cur.fetchone()
			session['tidakbersekolahlagikelas7']=str(jumlahtidakbersekolahlagikelastujuh[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_kelas_tertinggi LIKE '8' ")
			jumlahtidakbersekolahlagikelasdelapan=cur.fetchone()
			session['tidakbersekolahlagikelas8']=str(jumlahtidakbersekolahlagikelasdelapan[0])

			#MENGHITUNG IJAZAH TERTINGGI YANG DIMILIKI ANAK YANG MASIH BERSEKOLAH
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_ijazah_tertinggi LIKE '0' ")
			jumlahmasihsekolahtidakpunyaijazah=cur.fetchone()
			session['masihsekolahtidakpunyaijazah']=str(jumlahmasihsekolahtidakpunyaijazah[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_ijazah_tertinggi LIKE '1' ")
			jumlahmasihsekolahijazahsd=cur.fetchone()
			session['masihsekolahijazahsd']=str(jumlahmasihsekolahijazahsd[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_ijazah_tertinggi LIKE '2' ")
			jumlahmasihsekolahijazahsmp=cur.fetchone()
			session['masihsekolahijazahsmp']=str(jumlahmasihsekolahijazahsmp[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_ijazah_tertinggi LIKE '3' ")
			jumlahmasihsekolahijazahsma=cur.fetchone()
			session['masihsekolahijazahsma']=str(jumlahmasihsekolahijazahsma[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_ijazah_tertinggi LIKE '4' ")
			jumlahmasihsekolahijazahd1d2d3=cur.fetchone()
			session['masihsekolahijazahd1d2d3']=str(jumlahmasihsekolahijazahd1d2d3[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_ijazah_tertinggi LIKE '5' ")
			jumlahmasihsekolahijazahd4s1=cur.fetchone()
			session['masihsekolahijazahd4s1']=str(jumlahmasihsekolahijazahd4s1[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '1' AND 5th_keatas_ijazah_tertinggi LIKE '6' ")
			jumlahmasihsekolahijazas2s3=cur.fetchone()
			session['masihsekolahijazahs2s3']=str(jumlahmasihsekolahijazas2s3[0])

			#MENGHITUNG IJAZAH TERTINGGI YANG DIMILIKI ANAK TIDAK BERSEKOLAH LAGI
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_ijazah_tertinggi LIKE '0' ")
			jumlahtidaksekolahlagitidakpunyaijazah=cur.fetchone()
			session['tidaksekolahtidakpunyaijazah']=str(jumlahtidaksekolahlagitidakpunyaijazah[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_ijazah_tertinggi LIKE '1' ")
			jumlahtidaksekolahlagiijazahsd=cur.fetchone()
			session['tidaksekolahijazahsd']=str(jumlahtidaksekolahlagiijazahsd[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_ijazah_tertinggi LIKE '2' ")
			jumlahtidaksekolahlagiijazahsmp=cur.fetchone()
			session['tidaksekolahijazahsmp']=str(jumlahtidaksekolahlagiijazahsmp[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_ijazah_tertinggi LIKE '3' ")
			jumlahtidaksekolahlagiijazahsma=cur.fetchone()
			session['tidaksekolahijazahsma']=str(jumlahtidaksekolahlagiijazahsma[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_ijazah_tertinggi LIKE '4' ")
			jumlahtidaksekolahlagiijazahd1d2d3=cur.fetchone()
			session['tidaksekolahijazahd1d2d3']=str(jumlahtidaksekolahlagiijazahd1d2d3[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_ijazah_tertinggi LIKE '5' ")
			jumlahtidaksekolahlagiijazahd4s1=cur.fetchone()
			session['tidaksekolahijazahd4s1']=str(jumlahmasihsekolahijazahd4s1[0])
			cur.execute("SELECT COUNT(*) FROM `bdt_rumahtangga-"+session['kodeprop']+"`  WHERE desa_id='"+session['kodedesa']+"' AND 5th_keatas_partisipasi_sekolah LIKE '2' AND 5th_keatas_ijazah_tertinggi LIKE '6' ")
			jumlahtidaksekolahlagiijazahs2s3=cur.fetchone()
			session['tidaksekolahijazahs2s3']=str(jumlahtidaksekolahlagiijazahs2s3[0])


			return render_template('baru/statistikpartisipasisekolah.html')
		return redirect(url_for('index'))
	return redirect(url_for('index'))

